language: clang
sudo: required
dist: trusty
services:
  - docker

install:
  - gem install coveralls-lcov

# The fcntl line works around a bug where Travis truncates logs and fails.
script:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - make -f Makefile.docker
  - make -f Makefile.docker buildall

after_success:
  - coveralls-lcov /home/travis/build/milagro-crypto/milagro-crypto-c/target/LINUX_64BIT_COVERAGE/coverage/amcl.info
